version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7.0
    container_name: chathub-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: chathub
    volumes:
      - mongodb_data:/data/db
    networks:
      - chathub-network

volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  chathub-network:
    driver: bridge